### ISSUE TITLE
Tool is translating >1 paragraph at a time

### ISSUE THREAD

**Issue by Kentoseth** [bookfere/Ebook-Translator-Calibre-Plugin#148]
Hi there,

Excellent tool. I really appreciate it exists.

I'm having issues translating certain Arabic EPUBs that are translating more than what appears to be paragraphs. It looks like the entire `<span>` is acknowledged and being translated:

```
<div dir="rtl" id="book-container">
<hr/>
<a id='C5'></a><a id='C6'></a>
<span class="title">الباب الأول: في عقد الإمامة</span><br /><span class="title">مدخل</span><br /><span class="red">...</span><br />البَابُ الأَوَّلُ: فِي عَقٍدِ الْإِمَامَةِ<br />الْإِمَامَةُ1: مَوْضُوعَةٌ لِخِلَافَةِ النُّبُوَّةِ فِي حِرَاسَةِ الدِّينِ وَسِيَاسَةِ الدُّنْيَا، وَعَقْدُهَا لِمَنْ يَقُومُ بِهَا فِي الْأُمَّةِ وَاجِبٌ بِالْإِجْمَاعِ وَإِنْ شَذَّ عَنْهُمْ الْأَصَمُّ.<br />هَلْ الخِلَافَةُ وَاجَبَةٌ بِالشَّرْعِ أَمْ بِالْعَقْلِ؟<br />وَاخْتُلِفَ فِي وُجُوبِهَا2 هَلْ وَجَبَتْ بِالْعَقْلِ أَوْ بِالشَّرْعِ؟ فَقَالَتْ طَائِفَةٌ: وَجَبَتْ بِالْعَقْلِ لِمَا فِي طِبَاعِ الْعُقَلَاءِ مِنْ التَّسْلِيمِ لِزَعِيمٍ يَمْنَعُهُمْ مِنْ التَّظَالُمِ، وَيَفْصِلُ بَيْنَهُمْ فِي التَّنَازُعِ وَالتَّخَاصُمِ، وَلَوْلَا الْوُلَاةُ لَكَانُوا فَوْضَى مُهْمَلِينَ، وَهَمَجًا مُضَاعِينَ، وَقَدْ قَالَ الْأَفْوَهُ الْأَوْدِيُّ3، وَهُوَ شَاعِرٌ جَاهِلِيٌّ &quot;مِنْ الْبَسِيطِ&quot;:<br />لَا يَصْلُحُ النَّاسُ فَوْضَى لَا سَرَاةَ لَهُمْ <span class="red">...</span> وَلَا سَرَاةٌ إذَا جُهَّالُهُمْ سَادُوا<br />وَقَالَتْ طَائِفَةٌ أُخْرَى: بَلْ وَجَبَتْ بِالشَّرْعِ دُونَ الْعَقْلِ؛ لِأَنَّ الْإِمَامَ يَقُومُ بِأُمُورٍ شَرْعِيَّةٍ قَدْ<span class="footnote-hr">&nbsp;</span><span class="footnote">1 قلت: والإمامة والخلافة مصطلحان مترادفان، وإن كان مصطلح الخلاقة أسبق، ومصطلح الإمامة أكثر ما يتردَّد عند الشيعة، والإمامية منهم خاصة، لكنَّ المعنى يكاد يكون واحدًا، وهو: رئاسة عامَّة في أمر الدين والدنيا، كما قال التفتازاني، أو: هي خلافة الرسول -صلى الله عليه وسلم- في إقامة الدِّين وحفظ حوزة الملَّة، يجب اتباعه على كافَّة الأمة، كما قال عضد الدين الإيجي في شرح المواقف، أو: هي خلافةٌ عن النبي -صلى الله عليه وسلم- كما قال الشيخ رشيد رضا في كتابه الخلافة.<br />2 يقول الدكتور عبد الرزاق السنهوري -رحمه الله: إنَّ أهل السنَّة والمعتزلة يرون أنَّ الخلافة واجب شرعي، ولكنَّهم يختلفون في أساس هذا الوجوب؛ فأهل السُّنَّة يرون أنَّ سند وجوب الخلافة هو الإجماع، أمَّا الرأي الآخرِ وغالب أنصاره من المعتزلة، فيرى أنَّ سند الوجوب هو العقل، وهناك طائفة من المعتزلة ترى أنَّ سند وجوب الخلافة شرعيّ وعقليّ في واقت واحد، ويرى الشيعة كذلك وجوب إقامة الحكومة الإسلامية. &quot;فقه الخلافة وتطورها: ص 59&quot;.<br />3 الأفوه الأودي، هو صلاءة بن عمرو بن مالك، أبو ربيعة، من بني أود، من مذحج؛ شاعر يماني جاهلي، لقِّبَ بالأفوه لأنَّه كان غليظ الشفتين ظاهر الأسنان، كان سيِّدَ قومه وقائدهم في حروبهم، وهو أحد الحكماء والشعراء في عصره.</span>
</div>
<hr/>
<div class="center">الجزء: 1 ¦ الصفحة: 15</div>
</body>
</html>
```

The line breaks `<br>` are ignored and so entire chunks of text are translated, making it hard to read smaller portions (as the tool is meant to do).

![ebook-translate-bug](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/2989402/05bb004f-c18d-47b3-ac19-f0c0ec9733a3)

**Comment by bookfere** [comment]
Thank you for your feedback. We've fixed the bug you encountered. Additionally, your use case has inspired us to ensure that the translation has the correct text direction. You can visit the plugin's [homepage](https://translator.bookfere.com) to download the "__Rolling Version__," which includes the fixed version.

<img width="1003" alt="br-issue" src="https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/29969316/23d1d7a3-a69c-4ef3-98e1-f70ef99c1263">

**Comment by Kentoseth** [comment]
Thank you for the super fast bug fix.

Is the new rendering the same as the image you sent above? 

Or does each line break represent the place where the translated text will appear?

On small devices like Kindles and tablets, the size of the translation blocks were too big, so I had to move between 2-3 pages to read the translations each time.

It would be better to place the translations after each line break, so that it fits the small screens better.

**Comment by Kentoseth** [comment]
Hello. I hope you are well.

What is the status of this request?

I could try to help regarding the <br> issue for text blocks.

**Comment by Kentoseth** [comment]
Has this commit been included in the latest release?

I attempted to install V2.3.3 and the bug was not fixed.

I also downloaded the repo with the commit directly: https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/tree/a046c1eb011c76bcd3bff8bb184f4dc5b596b6f4

and the bug was still present.

I also tried the rolling release from the website and same outcome.

All 3 versions did not work.

**Comment by bookfere** [comment]
I just optimized the adding translation for line breaks, please try the latest Rolling Release.

**Comment by bookfere** [comment]
<img width="651" alt="screenshot" src="https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/29969316/32edf548-3741-4994-9084-6bc6ebda6206">

[risalah-murshid_translated.zip](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/14979813/risalah-murshid_translated.zip)

Did you restart Calibre after loading the new version of the plugin? I tested translating the sample you provided, and it yielded normal results.
